---
minimum_pre_commit_version: 4.0.0
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

ci:
  autofix_commit_msg: |
    fix: Apply automatic fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: "ci(pre-commits): bump pre-commit hooks"
  autoupdate_schedule: quarterly
  skip: [pip-compile]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["-f=lf"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes"]
        additional_dependencies: [tomli]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [--number]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-simple-breaks

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --base64-limit=4
          - --hex-limit=3

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: pip-compile
        name: compile requirements.txt
        entry: bash -c 'pip-compile --strip-extras --output-file=requirements.txt pyproject.toml > /dev/null'
        language: system
        pass_filenames: false
        files: requirements.txt|pyproject.toml
